// Code generated by ent, DO NOT EDIT.

package authorization

import (
	"moknito/binid"
	"moknito/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldDeletedAt, v))
}

// CodeConsumedAt applies equality check predicate on the "code_consumed_at" field. It's identical to CodeConsumedAtEQ.
func CodeConsumedAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCodeConsumedAt, v))
}

// ExpireAt applies equality check predicate on the "expire_at" field. It's identical to ExpireAtEQ.
func ExpireAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldExpireAt, v))
}

// RefreshExpireAt applies equality check predicate on the "refresh_expire_at" field. It's identical to RefreshExpireAtEQ.
func RefreshExpireAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldRefreshExpireAt, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldApplicationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Authorization {
	return predicate.Authorization(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Authorization {
	return predicate.Authorization(sql.FieldNotNull(FieldDeletedAt))
}

// ChallengeMethodEQ applies the EQ predicate on the "challenge_method" field.
func ChallengeMethodEQ(v ChallengeMethod) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldChallengeMethod, v))
}

// ChallengeMethodNEQ applies the NEQ predicate on the "challenge_method" field.
func ChallengeMethodNEQ(v ChallengeMethod) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldChallengeMethod, v))
}

// ChallengeMethodIn applies the In predicate on the "challenge_method" field.
func ChallengeMethodIn(vs ...ChallengeMethod) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldChallengeMethod, vs...))
}

// ChallengeMethodNotIn applies the NotIn predicate on the "challenge_method" field.
func ChallengeMethodNotIn(vs ...ChallengeMethod) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldChallengeMethod, vs...))
}

// CodeConsumedAtEQ applies the EQ predicate on the "code_consumed_at" field.
func CodeConsumedAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCodeConsumedAt, v))
}

// CodeConsumedAtNEQ applies the NEQ predicate on the "code_consumed_at" field.
func CodeConsumedAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldCodeConsumedAt, v))
}

// CodeConsumedAtIn applies the In predicate on the "code_consumed_at" field.
func CodeConsumedAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldCodeConsumedAt, vs...))
}

// CodeConsumedAtNotIn applies the NotIn predicate on the "code_consumed_at" field.
func CodeConsumedAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldCodeConsumedAt, vs...))
}

// CodeConsumedAtGT applies the GT predicate on the "code_consumed_at" field.
func CodeConsumedAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldCodeConsumedAt, v))
}

// CodeConsumedAtGTE applies the GTE predicate on the "code_consumed_at" field.
func CodeConsumedAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldCodeConsumedAt, v))
}

// CodeConsumedAtLT applies the LT predicate on the "code_consumed_at" field.
func CodeConsumedAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldCodeConsumedAt, v))
}

// CodeConsumedAtLTE applies the LTE predicate on the "code_consumed_at" field.
func CodeConsumedAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldCodeConsumedAt, v))
}

// CodeConsumedAtIsNil applies the IsNil predicate on the "code_consumed_at" field.
func CodeConsumedAtIsNil() predicate.Authorization {
	return predicate.Authorization(sql.FieldIsNull(FieldCodeConsumedAt))
}

// CodeConsumedAtNotNil applies the NotNil predicate on the "code_consumed_at" field.
func CodeConsumedAtNotNil() predicate.Authorization {
	return predicate.Authorization(sql.FieldNotNull(FieldCodeConsumedAt))
}

// ExpireAtEQ applies the EQ predicate on the "expire_at" field.
func ExpireAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldExpireAt, v))
}

// ExpireAtNEQ applies the NEQ predicate on the "expire_at" field.
func ExpireAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldExpireAt, v))
}

// ExpireAtIn applies the In predicate on the "expire_at" field.
func ExpireAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldExpireAt, vs...))
}

// ExpireAtNotIn applies the NotIn predicate on the "expire_at" field.
func ExpireAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldExpireAt, vs...))
}

// ExpireAtGT applies the GT predicate on the "expire_at" field.
func ExpireAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldExpireAt, v))
}

// ExpireAtGTE applies the GTE predicate on the "expire_at" field.
func ExpireAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldExpireAt, v))
}

// ExpireAtLT applies the LT predicate on the "expire_at" field.
func ExpireAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldExpireAt, v))
}

// ExpireAtLTE applies the LTE predicate on the "expire_at" field.
func ExpireAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldExpireAt, v))
}

// RefreshExpireAtEQ applies the EQ predicate on the "refresh_expire_at" field.
func RefreshExpireAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldRefreshExpireAt, v))
}

// RefreshExpireAtNEQ applies the NEQ predicate on the "refresh_expire_at" field.
func RefreshExpireAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldRefreshExpireAt, v))
}

// RefreshExpireAtIn applies the In predicate on the "refresh_expire_at" field.
func RefreshExpireAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldRefreshExpireAt, vs...))
}

// RefreshExpireAtNotIn applies the NotIn predicate on the "refresh_expire_at" field.
func RefreshExpireAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldRefreshExpireAt, vs...))
}

// RefreshExpireAtGT applies the GT predicate on the "refresh_expire_at" field.
func RefreshExpireAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldRefreshExpireAt, v))
}

// RefreshExpireAtGTE applies the GTE predicate on the "refresh_expire_at" field.
func RefreshExpireAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldRefreshExpireAt, v))
}

// RefreshExpireAtLT applies the LT predicate on the "refresh_expire_at" field.
func RefreshExpireAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldRefreshExpireAt, v))
}

// RefreshExpireAtLTE applies the LTE predicate on the "refresh_expire_at" field.
func RefreshExpireAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldRefreshExpireAt, v))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldApplicationID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...binid.BinId) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldUserID, vs...))
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.Application) predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Authorization) predicate.Authorization {
	return predicate.Authorization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Authorization) predicate.Authorization {
	return predicate.Authorization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Authorization) predicate.Authorization {
	return predicate.Authorization(sql.NotPredicates(p))
}
