// Code generated by ent, DO NOT EDIT.

package authorization

import (
	"moknito/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Authorization {
	return predicate.Authorization(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldDeletedAt, v))
}

// Challenge applies equality check predicate on the "challenge" field. It's identical to ChallengeEQ.
func Challenge(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldChallenge, v))
}

// ChallengeMethod applies equality check predicate on the "challenge_method" field. It's identical to ChallengeMethodEQ.
func ChallengeMethod(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldChallengeMethod, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCode, v))
}

// CodeExpireAt applies equality check predicate on the "code_expire_at" field. It's identical to CodeExpireAtEQ.
func CodeExpireAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCodeExpireAt, v))
}

// ExpireAt applies equality check predicate on the "expire_at" field. It's identical to ExpireAtEQ.
func ExpireAt(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldExpireAt, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldApplicationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Authorization {
	return predicate.Authorization(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Authorization {
	return predicate.Authorization(sql.FieldNotNull(FieldDeletedAt))
}

// ChallengeEQ applies the EQ predicate on the "challenge" field.
func ChallengeEQ(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldChallenge, v))
}

// ChallengeNEQ applies the NEQ predicate on the "challenge" field.
func ChallengeNEQ(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldChallenge, v))
}

// ChallengeIn applies the In predicate on the "challenge" field.
func ChallengeIn(vs ...[]byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldChallenge, vs...))
}

// ChallengeNotIn applies the NotIn predicate on the "challenge" field.
func ChallengeNotIn(vs ...[]byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldChallenge, vs...))
}

// ChallengeGT applies the GT predicate on the "challenge" field.
func ChallengeGT(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldChallenge, v))
}

// ChallengeGTE applies the GTE predicate on the "challenge" field.
func ChallengeGTE(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldChallenge, v))
}

// ChallengeLT applies the LT predicate on the "challenge" field.
func ChallengeLT(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldChallenge, v))
}

// ChallengeLTE applies the LTE predicate on the "challenge" field.
func ChallengeLTE(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldChallenge, v))
}

// ChallengeMethodEQ applies the EQ predicate on the "challenge_method" field.
func ChallengeMethodEQ(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldChallengeMethod, v))
}

// ChallengeMethodNEQ applies the NEQ predicate on the "challenge_method" field.
func ChallengeMethodNEQ(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldChallengeMethod, v))
}

// ChallengeMethodIn applies the In predicate on the "challenge_method" field.
func ChallengeMethodIn(vs ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldChallengeMethod, vs...))
}

// ChallengeMethodNotIn applies the NotIn predicate on the "challenge_method" field.
func ChallengeMethodNotIn(vs ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldChallengeMethod, vs...))
}

// ChallengeMethodGT applies the GT predicate on the "challenge_method" field.
func ChallengeMethodGT(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldChallengeMethod, v))
}

// ChallengeMethodGTE applies the GTE predicate on the "challenge_method" field.
func ChallengeMethodGTE(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldChallengeMethod, v))
}

// ChallengeMethodLT applies the LT predicate on the "challenge_method" field.
func ChallengeMethodLT(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldChallengeMethod, v))
}

// ChallengeMethodLTE applies the LTE predicate on the "challenge_method" field.
func ChallengeMethodLTE(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldChallengeMethod, v))
}

// ChallengeMethodContains applies the Contains predicate on the "challenge_method" field.
func ChallengeMethodContains(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldContains(FieldChallengeMethod, v))
}

// ChallengeMethodHasPrefix applies the HasPrefix predicate on the "challenge_method" field.
func ChallengeMethodHasPrefix(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldHasPrefix(FieldChallengeMethod, v))
}

// ChallengeMethodHasSuffix applies the HasSuffix predicate on the "challenge_method" field.
func ChallengeMethodHasSuffix(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldHasSuffix(FieldChallengeMethod, v))
}

// ChallengeMethodEqualFold applies the EqualFold predicate on the "challenge_method" field.
func ChallengeMethodEqualFold(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEqualFold(FieldChallengeMethod, v))
}

// ChallengeMethodContainsFold applies the ContainsFold predicate on the "challenge_method" field.
func ChallengeMethodContainsFold(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldContainsFold(FieldChallengeMethod, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...[]byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...[]byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v []byte) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldCode, v))
}

// CodeExpireAtEQ applies the EQ predicate on the "code_expire_at" field.
func CodeExpireAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldCodeExpireAt, v))
}

// CodeExpireAtNEQ applies the NEQ predicate on the "code_expire_at" field.
func CodeExpireAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldCodeExpireAt, v))
}

// CodeExpireAtIn applies the In predicate on the "code_expire_at" field.
func CodeExpireAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldCodeExpireAt, vs...))
}

// CodeExpireAtNotIn applies the NotIn predicate on the "code_expire_at" field.
func CodeExpireAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldCodeExpireAt, vs...))
}

// CodeExpireAtGT applies the GT predicate on the "code_expire_at" field.
func CodeExpireAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldCodeExpireAt, v))
}

// CodeExpireAtGTE applies the GTE predicate on the "code_expire_at" field.
func CodeExpireAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldCodeExpireAt, v))
}

// CodeExpireAtLT applies the LT predicate on the "code_expire_at" field.
func CodeExpireAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldCodeExpireAt, v))
}

// CodeExpireAtLTE applies the LTE predicate on the "code_expire_at" field.
func CodeExpireAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldCodeExpireAt, v))
}

// ExpireAtEQ applies the EQ predicate on the "expire_at" field.
func ExpireAtEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldExpireAt, v))
}

// ExpireAtNEQ applies the NEQ predicate on the "expire_at" field.
func ExpireAtNEQ(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldExpireAt, v))
}

// ExpireAtIn applies the In predicate on the "expire_at" field.
func ExpireAtIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldExpireAt, vs...))
}

// ExpireAtNotIn applies the NotIn predicate on the "expire_at" field.
func ExpireAtNotIn(vs ...time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldExpireAt, vs...))
}

// ExpireAtGT applies the GT predicate on the "expire_at" field.
func ExpireAtGT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldExpireAt, v))
}

// ExpireAtGTE applies the GTE predicate on the "expire_at" field.
func ExpireAtGTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldExpireAt, v))
}

// ExpireAtLT applies the LT predicate on the "expire_at" field.
func ExpireAtLT(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldExpireAt, v))
}

// ExpireAtLTE applies the LTE predicate on the "expire_at" field.
func ExpireAtLTE(v time.Time) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldExpireAt, v))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldApplicationID, vs...))
}

// ApplicationIDGT applies the GT predicate on the "application_id" field.
func ApplicationIDGT(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldApplicationID, v))
}

// ApplicationIDGTE applies the GTE predicate on the "application_id" field.
func ApplicationIDGTE(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldApplicationID, v))
}

// ApplicationIDLT applies the LT predicate on the "application_id" field.
func ApplicationIDLT(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldApplicationID, v))
}

// ApplicationIDLTE applies the LTE predicate on the "application_id" field.
func ApplicationIDLTE(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldApplicationID, v))
}

// ApplicationIDContains applies the Contains predicate on the "application_id" field.
func ApplicationIDContains(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldContains(FieldApplicationID, v))
}

// ApplicationIDHasPrefix applies the HasPrefix predicate on the "application_id" field.
func ApplicationIDHasPrefix(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldHasPrefix(FieldApplicationID, v))
}

// ApplicationIDHasSuffix applies the HasSuffix predicate on the "application_id" field.
func ApplicationIDHasSuffix(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldHasSuffix(FieldApplicationID, v))
}

// ApplicationIDEqualFold applies the EqualFold predicate on the "application_id" field.
func ApplicationIDEqualFold(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEqualFold(FieldApplicationID, v))
}

// ApplicationIDContainsFold applies the ContainsFold predicate on the "application_id" field.
func ApplicationIDContainsFold(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldContainsFold(FieldApplicationID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Authorization {
	return predicate.Authorization(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Authorization {
	return predicate.Authorization(sql.FieldContainsFold(FieldUserID, v))
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.Application) predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Authorization {
	return predicate.Authorization(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Authorization) predicate.Authorization {
	return predicate.Authorization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Authorization) predicate.Authorization {
	return predicate.Authorization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Authorization) predicate.Authorization {
	return predicate.Authorization(sql.NotPredicates(p))
}
