package token

const SIGNATURE_KEY_ENV_LEN = 44
const SIGNATURE_KEY_LEN = 32
const SIGNATURE_LEN = 32
const SIGNATURE_ENCODED_LEN = 43

const TOKEN_TYPE_AUTHENTICATION = "authentication"
const TOKEN_TYPE_AUTHORIZATION = "authorization"
const TOKEN_TYPE_REFRESH = "refresh"
const BUNDLE_TOKEN_TYPE_BEARER = "bearer"
const AUTHENTICATED_TOKEN_VERSION = "0.0.1"
