// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 256},
		{Name: "domain", Type: field.TypeString, Unique: true, Size: 256},
		{Name: "redirect", Type: field.TypeString, Unique: true, Size: 512},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
	}
	// AuthenticationsColumns holds the columns for the "authentications" table.
	AuthenticationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "ip", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "expire_at", Type: field.TypeTime},
		{Name: "logout_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeString, SchemaType: map[string]string{"mysql": "binary(16)"}},
	}
	// AuthenticationsTable holds the schema information for the "authentications" table.
	AuthenticationsTable = &schema.Table{
		Name:       "authentications",
		Columns:    AuthenticationsColumns,
		PrimaryKey: []*schema.Column{AuthenticationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "authentications_users_authentications",
				Columns:    []*schema.Column{AuthenticationsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AuthorizationsColumns holds the columns for the "authorizations" table.
	AuthorizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "code", Type: field.TypeBytes, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "challenge", Type: field.TypeBytes, SchemaType: map[string]string{"mysql": "binary(32)"}},
		{Name: "expire_at", Type: field.TypeTime},
		{Name: "application_id", Type: field.TypeString, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "user_id", Type: field.TypeString, SchemaType: map[string]string{"mysql": "binary(16)"}},
	}
	// AuthorizationsTable holds the schema information for the "authorizations" table.
	AuthorizationsTable = &schema.Table{
		Name:       "authorizations",
		Columns:    AuthorizationsColumns,
		PrimaryKey: []*schema.Column{AuthorizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "authorizations_applications_application",
				Columns:    []*schema.Column{AuthorizationsColumns[7]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "authorizations_users_authorizations",
				Columns:    []*schema.Column{AuthorizationsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OwnedAppsColumns holds the columns for the "owned_apps" table.
	OwnedAppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 256},
		{Name: "domain", Type: field.TypeString, Size: 256},
		{Name: "application_id", Type: field.TypeString, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "user_id", Type: field.TypeString, SchemaType: map[string]string{"mysql": "binary(16)"}},
	}
	// OwnedAppsTable holds the schema information for the "owned_apps" table.
	OwnedAppsTable = &schema.Table{
		Name:       "owned_apps",
		Columns:    OwnedAppsColumns,
		PrimaryKey: []*schema.Column{OwnedAppsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "owned_apps_applications_application",
				Columns:    []*schema.Column{OwnedAppsColumns[6]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "owned_apps_users_owned_apps",
				Columns:    []*schema.Column{OwnedAppsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 256},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 256},
		{Name: "pwhash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApplicationsTable,
		AuthenticationsTable,
		AuthorizationsTable,
		OwnedAppsTable,
		UsersTable,
	}
)

func init() {
	AuthenticationsTable.ForeignKeys[0].RefTable = UsersTable
	AuthorizationsTable.ForeignKeys[0].RefTable = ApplicationsTable
	AuthorizationsTable.ForeignKeys[1].RefTable = UsersTable
	OwnedAppsTable.ForeignKeys[0].RefTable = ApplicationsTable
	OwnedAppsTable.ForeignKeys[1].RefTable = UsersTable
}
