// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moknito/ent/authorizedapp"
	"moknito/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizedAppUpdate is the builder for updating AuthorizedApp entities.
type AuthorizedAppUpdate struct {
	config
	hooks    []Hook
	mutation *AuthorizedAppMutation
}

// Where appends a list predicates to the AuthorizedAppUpdate builder.
func (_u *AuthorizedAppUpdate) Where(ps ...predicate.AuthorizedApp) *AuthorizedAppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthorizedAppUpdate) SetUpdatedAt(v time.Time) *AuthorizedAppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthorizedAppUpdate) SetDeletedAt(v time.Time) *AuthorizedAppUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthorizedAppUpdate) SetNillableDeletedAt(v *time.Time) *AuthorizedAppUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthorizedAppUpdate) ClearDeletedAt() *AuthorizedAppUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AuthorizedAppMutation object of the builder.
func (_u *AuthorizedAppUpdate) Mutation() *AuthorizedAppMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthorizedAppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthorizedAppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthorizedAppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthorizedAppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthorizedAppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authorizedapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthorizedAppUpdate) check() error {
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthorizedApp.application"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthorizedApp.user"`)
	}
	return nil
}

func (_u *AuthorizedAppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authorizedapp.Table, authorizedapp.Columns, sqlgraph.NewFieldSpec(authorizedapp.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authorizedapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authorizedapp.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authorizedapp.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorizedapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthorizedAppUpdateOne is the builder for updating a single AuthorizedApp entity.
type AuthorizedAppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthorizedAppMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthorizedAppUpdateOne) SetUpdatedAt(v time.Time) *AuthorizedAppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthorizedAppUpdateOne) SetDeletedAt(v time.Time) *AuthorizedAppUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthorizedAppUpdateOne) SetNillableDeletedAt(v *time.Time) *AuthorizedAppUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthorizedAppUpdateOne) ClearDeletedAt() *AuthorizedAppUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AuthorizedAppMutation object of the builder.
func (_u *AuthorizedAppUpdateOne) Mutation() *AuthorizedAppMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthorizedAppUpdate builder.
func (_u *AuthorizedAppUpdateOne) Where(ps ...predicate.AuthorizedApp) *AuthorizedAppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthorizedAppUpdateOne) Select(field string, fields ...string) *AuthorizedAppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthorizedApp entity.
func (_u *AuthorizedAppUpdateOne) Save(ctx context.Context) (*AuthorizedApp, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthorizedAppUpdateOne) SaveX(ctx context.Context) *AuthorizedApp {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthorizedAppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthorizedAppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthorizedAppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authorizedapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthorizedAppUpdateOne) check() error {
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthorizedApp.application"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthorizedApp.user"`)
	}
	return nil
}

func (_u *AuthorizedAppUpdateOne) sqlSave(ctx context.Context) (_node *AuthorizedApp, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authorizedapp.Table, authorizedapp.Columns, sqlgraph.NewFieldSpec(authorizedapp.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthorizedApp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authorizedapp.FieldID)
		for _, f := range fields {
			if !authorizedapp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authorizedapp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authorizedapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authorizedapp.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authorizedapp.FieldDeletedAt, field.TypeTime)
	}
	_node = &AuthorizedApp{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorizedapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
