// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moknito/ent/authentication"
	"moknito/ent/predicate"
	"moknito/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthenticationUpdate is the builder for updating Authentication entities.
type AuthenticationUpdate struct {
	config
	hooks    []Hook
	mutation *AuthenticationMutation
}

// Where appends a list predicates to the AuthenticationUpdate builder.
func (_u *AuthenticationUpdate) Where(ps ...predicate.Authentication) *AuthenticationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthenticationUpdate) SetUpdatedAt(v time.Time) *AuthenticationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthenticationUpdate) SetDeletedAt(v time.Time) *AuthenticationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthenticationUpdate) SetNillableDeletedAt(v *time.Time) *AuthenticationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthenticationUpdate) ClearDeletedAt() *AuthenticationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuthenticationUpdate) SetIP(v string) *AuthenticationUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuthenticationUpdate) SetNillableIP(v *string) *AuthenticationUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuthenticationUpdate) ClearIP() *AuthenticationUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuthenticationUpdate) SetUserAgent(v string) *AuthenticationUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuthenticationUpdate) SetNillableUserAgent(v *string) *AuthenticationUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuthenticationUpdate) ClearUserAgent() *AuthenticationUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetLogoutAt sets the "logout_at" field.
func (_u *AuthenticationUpdate) SetLogoutAt(v time.Time) *AuthenticationUpdate {
	_u.mutation.SetLogoutAt(v)
	return _u
}

// SetNillableLogoutAt sets the "logout_at" field if the given value is not nil.
func (_u *AuthenticationUpdate) SetNillableLogoutAt(v *time.Time) *AuthenticationUpdate {
	if v != nil {
		_u.SetLogoutAt(*v)
	}
	return _u
}

// ClearLogoutAt clears the value of the "logout_at" field.
func (_u *AuthenticationUpdate) ClearLogoutAt() *AuthenticationUpdate {
	_u.mutation.ClearLogoutAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AuthenticationUpdate) SetUserID(id string) *AuthenticationUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AuthenticationUpdate) SetUser(v *User) *AuthenticationUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AuthenticationMutation object of the builder.
func (_u *AuthenticationUpdate) Mutation() *AuthenticationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthenticationUpdate) ClearUser() *AuthenticationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthenticationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthenticationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthenticationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthenticationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthenticationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authentication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthenticationUpdate) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := authentication.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Authentication.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := authentication.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Authentication.user_agent": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Authentication.user"`)
	}
	return nil
}

func (_u *AuthenticationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authentication.Table, authentication.Columns, sqlgraph.NewFieldSpec(authentication.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authentication.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authentication.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authentication.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(authentication.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(authentication.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(authentication.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(authentication.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.LogoutAt(); ok {
		_spec.SetField(authentication.FieldLogoutAt, field.TypeTime, value)
	}
	if _u.mutation.LogoutAtCleared() {
		_spec.ClearField(authentication.FieldLogoutAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authentication.UserTable,
			Columns: []string{authentication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authentication.UserTable,
			Columns: []string{authentication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authentication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthenticationUpdateOne is the builder for updating a single Authentication entity.
type AuthenticationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthenticationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthenticationUpdateOne) SetUpdatedAt(v time.Time) *AuthenticationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthenticationUpdateOne) SetDeletedAt(v time.Time) *AuthenticationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthenticationUpdateOne) SetNillableDeletedAt(v *time.Time) *AuthenticationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthenticationUpdateOne) ClearDeletedAt() *AuthenticationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuthenticationUpdateOne) SetIP(v string) *AuthenticationUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuthenticationUpdateOne) SetNillableIP(v *string) *AuthenticationUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuthenticationUpdateOne) ClearIP() *AuthenticationUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuthenticationUpdateOne) SetUserAgent(v string) *AuthenticationUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuthenticationUpdateOne) SetNillableUserAgent(v *string) *AuthenticationUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuthenticationUpdateOne) ClearUserAgent() *AuthenticationUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetLogoutAt sets the "logout_at" field.
func (_u *AuthenticationUpdateOne) SetLogoutAt(v time.Time) *AuthenticationUpdateOne {
	_u.mutation.SetLogoutAt(v)
	return _u
}

// SetNillableLogoutAt sets the "logout_at" field if the given value is not nil.
func (_u *AuthenticationUpdateOne) SetNillableLogoutAt(v *time.Time) *AuthenticationUpdateOne {
	if v != nil {
		_u.SetLogoutAt(*v)
	}
	return _u
}

// ClearLogoutAt clears the value of the "logout_at" field.
func (_u *AuthenticationUpdateOne) ClearLogoutAt() *AuthenticationUpdateOne {
	_u.mutation.ClearLogoutAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AuthenticationUpdateOne) SetUserID(id string) *AuthenticationUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AuthenticationUpdateOne) SetUser(v *User) *AuthenticationUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AuthenticationMutation object of the builder.
func (_u *AuthenticationUpdateOne) Mutation() *AuthenticationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthenticationUpdateOne) ClearUser() *AuthenticationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AuthenticationUpdate builder.
func (_u *AuthenticationUpdateOne) Where(ps ...predicate.Authentication) *AuthenticationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthenticationUpdateOne) Select(field string, fields ...string) *AuthenticationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Authentication entity.
func (_u *AuthenticationUpdateOne) Save(ctx context.Context) (*Authentication, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthenticationUpdateOne) SaveX(ctx context.Context) *Authentication {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthenticationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthenticationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthenticationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authentication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthenticationUpdateOne) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := authentication.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Authentication.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := authentication.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Authentication.user_agent": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Authentication.user"`)
	}
	return nil
}

func (_u *AuthenticationUpdateOne) sqlSave(ctx context.Context) (_node *Authentication, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authentication.Table, authentication.Columns, sqlgraph.NewFieldSpec(authentication.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Authentication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authentication.FieldID)
		for _, f := range fields {
			if !authentication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authentication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authentication.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authentication.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authentication.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(authentication.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(authentication.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(authentication.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(authentication.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.LogoutAt(); ok {
		_spec.SetField(authentication.FieldLogoutAt, field.TypeTime, value)
	}
	if _u.mutation.LogoutAtCleared() {
		_spec.ClearField(authentication.FieldLogoutAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authentication.UserTable,
			Columns: []string{authentication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authentication.UserTable,
			Columns: []string{authentication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Authentication{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authentication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
