// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moknito/ent/authorization"
	"moknito/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizationCreate is the builder for creating a Authorization entity.
type AuthorizationCreate struct {
	config
	mutation *AuthorizationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthorizationCreate) SetCreatedAt(v time.Time) *AuthorizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthorizationCreate) SetNillableCreatedAt(v *time.Time) *AuthorizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthorizationCreate) SetUpdatedAt(v time.Time) *AuthorizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthorizationCreate) SetNillableUpdatedAt(v *time.Time) *AuthorizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AuthorizationCreate) SetDeletedAt(v time.Time) *AuthorizationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AuthorizationCreate) SetNillableDeletedAt(v *time.Time) *AuthorizationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetApplication sets the "application" field.
func (_c *AuthorizationCreate) SetApplication(v string) *AuthorizationCreate {
	_c.mutation.SetApplication(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *AuthorizationCreate) SetDomain(v string) *AuthorizationCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AuthorizationCreate) SetClientID(v string) *AuthorizationCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AuthorizationCreate) SetID(v string) *AuthorizationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AuthorizationCreate) SetUserID(id string) *AuthorizationCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AuthorizationCreate) SetUser(v *User) *AuthorizationCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AuthorizationMutation object of the builder.
func (_c *AuthorizationCreate) Mutation() *AuthorizationMutation {
	return _c.mutation
}

// Save creates the Authorization in the database.
func (_c *AuthorizationCreate) Save(ctx context.Context) (*Authorization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthorizationCreate) SaveX(ctx context.Context) *Authorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthorizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthorizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthorizationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authorization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authorization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthorizationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Authorization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Authorization.updated_at"`)}
	}
	if _, ok := _c.mutation.Application(); !ok {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required field "Authorization.application"`)}
	}
	if v, ok := _c.mutation.Application(); ok {
		if err := authorization.ApplicationValidator(v); err != nil {
			return &ValidationError{Name: "application", err: fmt.Errorf(`ent: validator failed for field "Authorization.application": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Authorization.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := authorization.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Authorization.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "Authorization.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := authorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Authorization.client_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := authorization.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Authorization.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Authorization.user"`)}
	}
	return nil
}

func (_c *AuthorizationCreate) sqlSave(ctx context.Context) (*Authorization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Authorization.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthorizationCreate) createSpec() (*Authorization, *sqlgraph.CreateSpec) {
	var (
		_node = &Authorization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authorization.Table, sqlgraph.NewFieldSpec(authorization.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authorization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authorization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(authorization.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Application(); ok {
		_spec.SetField(authorization.FieldApplication, field.TypeString, value)
		_node.Application = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(authorization.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(authorization.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authorization.UserTable,
			Columns: []string{authorization.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_authorizations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuthorizationCreateBulk is the builder for creating many Authorization entities in bulk.
type AuthorizationCreateBulk struct {
	config
	err      error
	builders []*AuthorizationCreate
}

// Save creates the Authorization entities in the database.
func (_c *AuthorizationCreateBulk) Save(ctx context.Context) ([]*Authorization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Authorization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthorizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthorizationCreateBulk) SaveX(ctx context.Context) []*Authorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthorizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthorizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
