// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moknito/ent/application"
	"moknito/ent/ownedapp"
	"moknito/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OwnedAppCreate is the builder for creating a OwnedApp entity.
type OwnedAppCreate struct {
	config
	mutation *OwnedAppMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OwnedAppCreate) SetCreatedAt(v time.Time) *OwnedAppCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OwnedAppCreate) SetNillableCreatedAt(v *time.Time) *OwnedAppCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OwnedAppCreate) SetUpdatedAt(v time.Time) *OwnedAppCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OwnedAppCreate) SetNillableUpdatedAt(v *time.Time) *OwnedAppCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OwnedAppCreate) SetDeletedAt(v time.Time) *OwnedAppCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OwnedAppCreate) SetNillableDeletedAt(v *time.Time) *OwnedAppCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OwnedAppCreate) SetName(v string) *OwnedAppCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *OwnedAppCreate) SetDomain(v string) *OwnedAppCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetApplicationID sets the "application_id" field.
func (_c *OwnedAppCreate) SetApplicationID(v string) *OwnedAppCreate {
	_c.mutation.SetApplicationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OwnedAppCreate) SetUserID(v string) *OwnedAppCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OwnedAppCreate) SetID(v string) *OwnedAppCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OwnedAppCreate) SetUser(v *User) *OwnedAppCreate {
	return _c.SetUserID(v.ID)
}

// SetApplication sets the "application" edge to the Application entity.
func (_c *OwnedAppCreate) SetApplication(v *Application) *OwnedAppCreate {
	return _c.SetApplicationID(v.ID)
}

// Mutation returns the OwnedAppMutation object of the builder.
func (_c *OwnedAppCreate) Mutation() *OwnedAppMutation {
	return _c.mutation
}

// Save creates the OwnedApp in the database.
func (_c *OwnedAppCreate) Save(ctx context.Context) (*OwnedApp, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OwnedAppCreate) SaveX(ctx context.Context) *OwnedApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OwnedAppCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OwnedAppCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OwnedAppCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ownedapp.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ownedapp.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OwnedAppCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OwnedApp.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OwnedApp.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OwnedApp.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ownedapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OwnedApp.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "OwnedApp.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := ownedapp.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "OwnedApp.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "OwnedApp.application_id"`)}
	}
	if v, ok := _c.mutation.ApplicationID(); ok {
		if err := ownedapp.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "OwnedApp.application_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OwnedApp.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := ownedapp.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OwnedApp.user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := ownedapp.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "OwnedApp.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OwnedApp.user"`)}
	}
	if len(_c.mutation.ApplicationIDs()) == 0 {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required edge "OwnedApp.application"`)}
	}
	return nil
}

func (_c *OwnedAppCreate) sqlSave(ctx context.Context) (*OwnedApp, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OwnedApp.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OwnedAppCreate) createSpec() (*OwnedApp, *sqlgraph.CreateSpec) {
	var (
		_node = &OwnedApp{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ownedapp.Table, sqlgraph.NewFieldSpec(ownedapp.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ownedapp.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ownedapp.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(ownedapp.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ownedapp.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(ownedapp.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ownedapp.UserTable,
			Columns: []string{ownedapp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ownedapp.ApplicationTable,
			Columns: []string{ownedapp.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OwnedAppCreateBulk is the builder for creating many OwnedApp entities in bulk.
type OwnedAppCreateBulk struct {
	config
	err      error
	builders []*OwnedAppCreate
}

// Save creates the OwnedApp entities in the database.
func (_c *OwnedAppCreateBulk) Save(ctx context.Context) ([]*OwnedApp, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OwnedApp, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OwnedAppMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OwnedAppCreateBulk) SaveX(ctx context.Context) []*OwnedApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OwnedAppCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OwnedAppCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
