// Code generated by ent, DO NOT EDIT.

package ent

import (
	"moknito/ent/authentication"
	"moknito/ent/authorization"
	"moknito/ent/schema"
	"moknito/ent/session"
	"moknito/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authenticationMixin := schema.Authentication{}.Mixin()
	authenticationMixinFields0 := authenticationMixin[0].Fields()
	_ = authenticationMixinFields0
	authenticationFields := schema.Authentication{}.Fields()
	_ = authenticationFields
	// authenticationDescCreatedAt is the schema descriptor for created_at field.
	authenticationDescCreatedAt := authenticationMixinFields0[0].Descriptor()
	// authentication.DefaultCreatedAt holds the default value on creation for the created_at field.
	authentication.DefaultCreatedAt = authenticationDescCreatedAt.Default.(func() time.Time)
	// authenticationDescUpdatedAt is the schema descriptor for updated_at field.
	authenticationDescUpdatedAt := authenticationMixinFields0[1].Descriptor()
	// authentication.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authentication.DefaultUpdatedAt = authenticationDescUpdatedAt.Default.(func() time.Time)
	// authentication.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authentication.UpdateDefaultUpdatedAt = authenticationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authenticationDescID is the schema descriptor for id field.
	authenticationDescID := authenticationFields[0].Descriptor()
	// authentication.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authentication.IDValidator = authenticationDescID.Validators[0].(func(string) error)
	authorizationMixin := schema.Authorization{}.Mixin()
	authorizationMixinFields0 := authorizationMixin[0].Fields()
	_ = authorizationMixinFields0
	authorizationFields := schema.Authorization{}.Fields()
	_ = authorizationFields
	// authorizationDescCreatedAt is the schema descriptor for created_at field.
	authorizationDescCreatedAt := authorizationMixinFields0[0].Descriptor()
	// authorization.DefaultCreatedAt holds the default value on creation for the created_at field.
	authorization.DefaultCreatedAt = authorizationDescCreatedAt.Default.(func() time.Time)
	// authorizationDescUpdatedAt is the schema descriptor for updated_at field.
	authorizationDescUpdatedAt := authorizationMixinFields0[1].Descriptor()
	// authorization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authorization.DefaultUpdatedAt = authorizationDescUpdatedAt.Default.(func() time.Time)
	// authorization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authorization.UpdateDefaultUpdatedAt = authorizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authorizationDescApplication is the schema descriptor for application field.
	authorizationDescApplication := authorizationFields[1].Descriptor()
	// authorization.ApplicationValidator is a validator for the "application" field. It is called by the builders before save.
	authorization.ApplicationValidator = authorizationDescApplication.Validators[0].(func(string) error)
	// authorizationDescDomain is the schema descriptor for domain field.
	authorizationDescDomain := authorizationFields[2].Descriptor()
	// authorization.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	authorization.DomainValidator = authorizationDescDomain.Validators[0].(func(string) error)
	// authorizationDescClientID is the schema descriptor for client_id field.
	authorizationDescClientID := authorizationFields[3].Descriptor()
	// authorization.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	authorization.ClientIDValidator = authorizationDescClientID.Validators[0].(func(string) error)
	// authorizationDescID is the schema descriptor for id field.
	authorizationDescID := authorizationFields[0].Descriptor()
	// authorization.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authorization.IDValidator = authorizationDescID.Validators[0].(func(string) error)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinFields0 := sessionMixin[0].Fields()
	_ = sessionMixinFields0
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionMixinFields0[0].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionMixinFields0[1].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescIP is the schema descriptor for ip field.
	sessionDescIP := sessionFields[2].Descriptor()
	// session.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	session.IPValidator = sessionDescIP.Validators[0].(func(string) error)
	// sessionDescUserAgent is the schema descriptor for user_agent field.
	sessionDescUserAgent := sessionFields[3].Descriptor()
	// session.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	session.UserAgentValidator = sessionDescUserAgent.Validators[0].(func(string) error)
	// sessionDescApplication is the schema descriptor for application field.
	sessionDescApplication := sessionFields[4].Descriptor()
	// session.ApplicationValidator is a validator for the "application" field. It is called by the builders before save.
	session.ApplicationValidator = sessionDescApplication.Validators[0].(func(string) error)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.IDValidator is a validator for the "id" field. It is called by the builders before save.
	session.IDValidator = sessionDescID.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPwhash is the schema descriptor for pwhash field.
	userDescPwhash := userFields[3].Descriptor()
	// user.PwhashValidator is a validator for the "pwhash" field. It is called by the builders before save.
	user.PwhashValidator = userDescPwhash.Validators[0].(func(string) error)
	// userDescError is the schema descriptor for error field.
	userDescError := userFields[4].Descriptor()
	// user.DefaultError holds the default value on creation for the error field.
	user.DefaultError = userDescError.Default.(int)
	// user.ErrorValidator is a validator for the "error" field. It is called by the builders before save.
	user.ErrorValidator = userDescError.Validators[0].(func(int) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
