// Code generated by ent, DO NOT EDIT.

package ent

import (
	"moknito/ent/application"
	"moknito/ent/authentication"
	"moknito/ent/authorization"
	"moknito/ent/authorizedapp"
	"moknito/ent/schema"
	"moknito/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	applicationMixin := schema.Application{}.Mixin()
	applicationMixinFields0 := applicationMixin[0].Fields()
	_ = applicationMixinFields0
	applicationFields := schema.Application{}.Fields()
	_ = applicationFields
	// applicationDescCreatedAt is the schema descriptor for created_at field.
	applicationDescCreatedAt := applicationMixinFields0[0].Descriptor()
	// application.DefaultCreatedAt holds the default value on creation for the created_at field.
	application.DefaultCreatedAt = applicationDescCreatedAt.Default.(func() time.Time)
	// applicationDescUpdatedAt is the schema descriptor for updated_at field.
	applicationDescUpdatedAt := applicationMixinFields0[1].Descriptor()
	// application.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	application.DefaultUpdatedAt = applicationDescUpdatedAt.Default.(func() time.Time)
	// application.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	application.UpdateDefaultUpdatedAt = applicationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// applicationDescName is the schema descriptor for name field.
	applicationDescName := applicationFields[1].Descriptor()
	// application.NameValidator is a validator for the "name" field. It is called by the builders before save.
	application.NameValidator = func() func(string) error {
		validators := applicationDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// applicationDescDomain is the schema descriptor for domain field.
	applicationDescDomain := applicationFields[2].Descriptor()
	// application.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	application.DomainValidator = func() func(string) error {
		validators := applicationDescDomain.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(domain string) error {
			for _, fn := range fns {
				if err := fn(domain); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// applicationDescRedirect is the schema descriptor for redirect field.
	applicationDescRedirect := applicationFields[3].Descriptor()
	// application.RedirectValidator is a validator for the "redirect" field. It is called by the builders before save.
	application.RedirectValidator = func() func(string) error {
		validators := applicationDescRedirect.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(redirect string) error {
			for _, fn := range fns {
				if err := fn(redirect); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// applicationDescID is the schema descriptor for id field.
	applicationDescID := applicationFields[0].Descriptor()
	// application.IDValidator is a validator for the "id" field. It is called by the builders before save.
	application.IDValidator = applicationDescID.Validators[0].(func(string) error)
	authenticationMixin := schema.Authentication{}.Mixin()
	authenticationMixinFields0 := authenticationMixin[0].Fields()
	_ = authenticationMixinFields0
	authenticationFields := schema.Authentication{}.Fields()
	_ = authenticationFields
	// authenticationDescCreatedAt is the schema descriptor for created_at field.
	authenticationDescCreatedAt := authenticationMixinFields0[0].Descriptor()
	// authentication.DefaultCreatedAt holds the default value on creation for the created_at field.
	authentication.DefaultCreatedAt = authenticationDescCreatedAt.Default.(func() time.Time)
	// authenticationDescUpdatedAt is the schema descriptor for updated_at field.
	authenticationDescUpdatedAt := authenticationMixinFields0[1].Descriptor()
	// authentication.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authentication.DefaultUpdatedAt = authenticationDescUpdatedAt.Default.(func() time.Time)
	// authentication.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authentication.UpdateDefaultUpdatedAt = authenticationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authenticationDescIP is the schema descriptor for ip field.
	authenticationDescIP := authenticationFields[1].Descriptor()
	// authentication.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	authentication.IPValidator = authenticationDescIP.Validators[0].(func(string) error)
	// authenticationDescUserAgent is the schema descriptor for user_agent field.
	authenticationDescUserAgent := authenticationFields[2].Descriptor()
	// authentication.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	authentication.UserAgentValidator = authenticationDescUserAgent.Validators[0].(func(string) error)
	// authenticationDescUserID is the schema descriptor for user_id field.
	authenticationDescUserID := authenticationFields[5].Descriptor()
	// authentication.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	authentication.UserIDValidator = authenticationDescUserID.Validators[0].(func(string) error)
	// authenticationDescID is the schema descriptor for id field.
	authenticationDescID := authenticationFields[0].Descriptor()
	// authentication.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authentication.IDValidator = authenticationDescID.Validators[0].(func(string) error)
	authorizationMixin := schema.Authorization{}.Mixin()
	authorizationMixinFields0 := authorizationMixin[0].Fields()
	_ = authorizationMixinFields0
	authorizationFields := schema.Authorization{}.Fields()
	_ = authorizationFields
	// authorizationDescCreatedAt is the schema descriptor for created_at field.
	authorizationDescCreatedAt := authorizationMixinFields0[0].Descriptor()
	// authorization.DefaultCreatedAt holds the default value on creation for the created_at field.
	authorization.DefaultCreatedAt = authorizationDescCreatedAt.Default.(func() time.Time)
	// authorizationDescUpdatedAt is the schema descriptor for updated_at field.
	authorizationDescUpdatedAt := authorizationMixinFields0[1].Descriptor()
	// authorization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authorization.DefaultUpdatedAt = authorizationDescUpdatedAt.Default.(func() time.Time)
	// authorization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authorization.UpdateDefaultUpdatedAt = authorizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authorizationDescChallenge is the schema descriptor for challenge field.
	authorizationDescChallenge := authorizationFields[1].Descriptor()
	// authorization.ChallengeValidator is a validator for the "challenge" field. It is called by the builders before save.
	authorization.ChallengeValidator = authorizationDescChallenge.Validators[0].(func([]byte) error)
	// authorizationDescCode is the schema descriptor for code field.
	authorizationDescCode := authorizationFields[2].Descriptor()
	// authorization.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	authorization.CodeValidator = authorizationDescCode.Validators[0].(func([]byte) error)
	// authorizationDescApplicationID is the schema descriptor for application_id field.
	authorizationDescApplicationID := authorizationFields[5].Descriptor()
	// authorization.ApplicationIDValidator is a validator for the "application_id" field. It is called by the builders before save.
	authorization.ApplicationIDValidator = authorizationDescApplicationID.Validators[0].(func(string) error)
	// authorizationDescUserID is the schema descriptor for user_id field.
	authorizationDescUserID := authorizationFields[6].Descriptor()
	// authorization.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	authorization.UserIDValidator = authorizationDescUserID.Validators[0].(func(string) error)
	// authorizationDescID is the schema descriptor for id field.
	authorizationDescID := authorizationFields[0].Descriptor()
	// authorization.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authorization.IDValidator = authorizationDescID.Validators[0].(func(string) error)
	authorizedappMixin := schema.AuthorizedApp{}.Mixin()
	authorizedappMixinFields0 := authorizedappMixin[0].Fields()
	_ = authorizedappMixinFields0
	authorizedappFields := schema.AuthorizedApp{}.Fields()
	_ = authorizedappFields
	// authorizedappDescCreatedAt is the schema descriptor for created_at field.
	authorizedappDescCreatedAt := authorizedappMixinFields0[0].Descriptor()
	// authorizedapp.DefaultCreatedAt holds the default value on creation for the created_at field.
	authorizedapp.DefaultCreatedAt = authorizedappDescCreatedAt.Default.(func() time.Time)
	// authorizedappDescUpdatedAt is the schema descriptor for updated_at field.
	authorizedappDescUpdatedAt := authorizedappMixinFields0[1].Descriptor()
	// authorizedapp.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authorizedapp.DefaultUpdatedAt = authorizedappDescUpdatedAt.Default.(func() time.Time)
	// authorizedapp.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authorizedapp.UpdateDefaultUpdatedAt = authorizedappDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authorizedappDescApplicationID is the schema descriptor for application_id field.
	authorizedappDescApplicationID := authorizedappFields[1].Descriptor()
	// authorizedapp.ApplicationIDValidator is a validator for the "application_id" field. It is called by the builders before save.
	authorizedapp.ApplicationIDValidator = authorizedappDescApplicationID.Validators[0].(func(string) error)
	// authorizedappDescUserID is the schema descriptor for user_id field.
	authorizedappDescUserID := authorizedappFields[2].Descriptor()
	// authorizedapp.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	authorizedapp.UserIDValidator = authorizedappDescUserID.Validators[0].(func(string) error)
	// authorizedappDescID is the schema descriptor for id field.
	authorizedappDescID := authorizedappFields[0].Descriptor()
	// authorizedapp.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authorizedapp.IDValidator = authorizedappDescID.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPwhash is the schema descriptor for pwhash field.
	userDescPwhash := userFields[3].Descriptor()
	// user.PwhashValidator is a validator for the "pwhash" field. It is called by the builders before save.
	user.PwhashValidator = userDescPwhash.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
